title: "Shrouded Lands Wiki Mirror"
markdown: kramdown
baseurl: "/shrouded-lands"
url: ""

collections:
  wiki:
    output: true
    permalink: /wiki/:name/
    render_with_liquid: false

defaults:
  - scope:
      path: ""
      type: wiki
    values:
      layout: wiki_page

exclude:
  - _site
  - .sass-cache
  - .jekyll-cache
  - vendor
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
